language: ruby
install: bundle install
rvm:
  - 2.2.1
script:
  - RUBYOPT=-W0 bundle exec rake test
git:
  depth: 10
notifications:
  email: false
before_install:
  - gem install bundler -v '= 1.10.6'
